# https://taskfile.dev

version: "3"

vars:
  BINARY_NAME: otel-journal-gatewayd-forwarder
  E2E_IMAGE: otel-journal-e2e-test
  E2E_RESULTS: .e2e-results

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the project in debug mode
    cmds:
      - cargo build

  build:release:
    desc: Build the project in release mode
    cmds:
      - cargo build --release

  test:
    desc: Run unit tests
    cmds:
      - cargo test

  test:verbose:
    desc: Run unit tests with output
    cmds:
      - cargo test -- --nocapture

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  check:
    desc: Run all checks (fmt, clippy, test)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # E2E Testing
  e2e:build:
    desc: Build the e2e test container image
    cmds:
      - podman build -f Containerfile.e2e -t {{.E2E_IMAGE}} .

  e2e:run:
    desc: Run e2e tests in container
    deps:
      - e2e:build
    cmds:
      - ./e2e/run-in-container.sh {{.E2E_IMAGE}} {{.E2E_RESULTS}}

  e2e:shell:
    desc: Get a shell in the e2e container for debugging
    deps:
      - e2e:build
    cmds:
      - podman run --rm -it --privileged {{.E2E_IMAGE}} /bin/bash

  e2e:logs:
    desc: Show captured logs from last e2e run
    cmds:
      - jq -s '[.[].resourceLogs[]?.scopeLogs[]?.logRecords[]?] | length' {{.E2E_RESULTS}}/logs.json
      - jq -s '.[].resourceLogs[].scopeLogs[].logRecords[].body.stringValue' {{.E2E_RESULTS}}/logs.json | head -10

  e2e:clean:
    desc: Remove e2e test image and results
    cmds:
      - podman rmi {{.E2E_IMAGE}} || true
      - rm -rf {{.E2E_RESULTS}}

  # Development helpers
  run:
    desc: Run with example config (requires config.toml)
    cmds:
      - cargo run -- -c config.toml

  run:validate:
    desc: Validate configuration
    cmds:
      - cargo run -- -c config.toml --validate

  run:once:
    desc: Run once and exit (useful for testing)
    cmds:
      - cargo run -- -c config.toml --once -vv
