# https://taskfile.dev

version: "3"

vars:
  BINARY_NAME: otel-journal-gatewayd-forwarder
  E2E_IMAGE_PREFIX: otel-journal-e2e
  E2E_RESULTS: .e2e-results
  # Default distro for single-distro commands
  DISTRO: fedora

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the project in debug mode
    cmds:
      - cargo build

  build:release:
    desc: Build the project in release mode
    cmds:
      - cargo build --release

  test:
    desc: Run unit tests
    cmds:
      - cargo test

  test:verbose:
    desc: Run unit tests with output
    cmds:
      - cargo test -- --nocapture

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy -- -D warnings

  check:
    desc: Run all checks (fmt, clippy, test)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # E2E Testing - Single Distro
  e2e:build:
    desc: "Build e2e test container for a distro (DISTRO=fedora|al2023|debian)"
    cmds:
      - podman build -f e2e/Containerfile --build-arg DISTRO={{.DISTRO}} -t {{.E2E_IMAGE_PREFIX}}-{{.DISTRO}} .

  e2e:run:
    desc: "Run e2e tests for a distro (DISTRO=fedora|al2023|debian)"
    deps:
      - e2e:build
    cmds:
      - ./e2e/run-in-container.sh {{.E2E_IMAGE_PREFIX}}-{{.DISTRO}} {{.E2E_RESULTS}}/{{.DISTRO}}

  e2e:shell:
    desc: "Get a shell in the e2e container for debugging (DISTRO=fedora|al2023|debian)"
    deps:
      - e2e:build
    cmds:
      - podman run --rm -it --privileged {{.E2E_IMAGE_PREFIX}}-{{.DISTRO}} /bin/bash

  # E2E Testing - All Distros
  e2e:build:all:
    desc: Build e2e test containers for all distros
    cmds:
      - task: e2e:build
        vars: { DISTRO: fedora }
      - task: e2e:build
        vars: { DISTRO: al2023 }
      - task: e2e:build
        vars: { DISTRO: debian }

  e2e:run:all:
    desc: Run e2e tests on all distros
    cmds:
      - task: e2e:run
        vars: { DISTRO: fedora }
      - task: e2e:run
        vars: { DISTRO: al2023 }
      - task: e2e:run
        vars: { DISTRO: debian }

  e2e:matrix:
    desc: Build and run e2e tests on all distros (full matrix)
    cmds:
      - task: e2e:build:all
      - task: e2e:run:all

  e2e:logs:
    desc: "Show captured logs from last e2e run (DISTRO=fedora|al2023|debian)"
    cmds:
      - jq -s '[.[].resourceLogs[]?.scopeLogs[]?.logRecords[]?] | length' {{.E2E_RESULTS}}/{{.DISTRO}}/logs.json
      - jq -s '.[].resourceLogs[].scopeLogs[].logRecords[].body.stringValue' {{.E2E_RESULTS}}/{{.DISTRO}}/logs.json | head -10

  e2e:clean:
    desc: Remove all e2e test images and results
    cmds:
      - podman rmi {{.E2E_IMAGE_PREFIX}}-fedora || true
      - podman rmi {{.E2E_IMAGE_PREFIX}}-al2023 || true
      - podman rmi {{.E2E_IMAGE_PREFIX}}-debian || true
      - rm -rf {{.E2E_RESULTS}}

  # Development helpers
  run:
    desc: Run with example config (requires config.toml)
    cmds:
      - cargo run -- -c config.toml

  run:validate:
    desc: Validate configuration
    cmds:
      - cargo run -- -c config.toml --validate

  run:once:
    desc: Run once and exit (useful for testing)
    cmds:
      - cargo run -- -c config.toml --once -vv
